# release.toml (at the root of your repo)
# may consider release-plz in future
consolidate-commits = true
shared-version = true
pre-release-hook = ["git-cliff", "--unreleased", "--tag", "{{version}}", "--prepend", "CHANGELOG.md"]
pre-release-commit-message = "chore: Release version {{version}}"