use sqlitex::{Connection, sqlitex};

#[sqlitex]
struct AppDatabase {
    init: sql!(
        "
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY NOT NULL,
            username TEXT NOT NULL,
            is_active BOOL NOT NULL
        )
    "
    ),

    add_user: sql!("INSERT INTO users (id, username, is_active) VALUES (?::REAL, ?, ?);"),

    get_active_users: sql!(
        "SELECT CAST (id AS REAL), username, is_active as active FROM users WHERE is_active = ?"
    ),

}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let conn = Connection::open_memory()?;
    let mut db = AppDatabase::new(conn);

    db.init()?;

    let bulk = [
        (0.0, "Alice".to_string(), true),
        (1.0, "Bob".to_string(), false),
        (2.0, "Charlie".to_string(), true),
    ];

    // the add_user_many is autogenerated even tho it wasnt specified when defining them in the struct above
    // All write statement would automatically have a _many function which you can use for bulk operations
    // Note that it is atomic and if you want fine grain control on how much to commit, use transactions
    db.add_user_many(&bulk)?;


    let active_users = db.get_active_users(true)?;

    for user in active_users {
        let user = user?;
        println!("{}, {}, {}", user.id, user.username, user.active);
    }

    // should print:
    // 0, Alice, true
    // 2, Charlie, true

    Ok(())
}

